oat-sa/tao-community

composer.json, composer.lock
Update taoProctoring from `8.13.1` to `8.13.2`
=> Release Sprint 78 - Update 1

composer.json, composer.lock
=> Sprint 71 Patch 6

composer.json, composer.lock
=> Sprint82 to Stress

composer.json, composer.lock
=> Udate Sprint89.1

composer.json, composer.lock
Fix issue in taoQtiTest with calculator's options
=> Fix taoQtiTest

composer.json
=> Hotfix release v0.95.1-alpha

composer.json, composer.lock
=> Release v0.95.2-alpha

composer.json, composer.lock
=> Release Sprint 95 Update 3

composer.json, composer.lock
=> Update tao-core to 24.5.1

composer.json, composer.lock
Related to:
- https://oat-sa.atlassian.net/browse/TAO-7690
- https://oat-sa.atlassian.net/browse/TAO-7771
- https://oat-sa.atlassian.net/browse/TAO-7801
Backport to Sprint 96.2
=> Backport/tao 7690/tao 7771/tao 7801/sprint96.2

composer.json, composer.lock
Sprint 103 Alpha Update 1 - re-release of previous because of missing tao-core version + un-built composer.lock
=> Sprint 103 Alpha Update 1

composer.json, composer.lock
=> sprint release 105

composer.json, composer.lock
Sprint 105.1
- [Hotfix] [TAO-7842](https://oat-sa.atlassian.net/browse/TAO-7842) Too much greedy empty check [#1297](https://github.com/oat-sa/extension-tao-itemqti/pull/1297)
=> Sprint 105.1

composer.json, composer.lock
Sprint 106.2
- [Hotfix] Transpiler issue with math keyword [#1307](https://github.com/oat-sa/extension-tao-itemqti/pull/1307)
=> Sprint 106.2 - fix taoQtiItem

composer.json, composer.lock
=> Sprint 107

composer.json, composer.lock
Sprint 109 update 5
- [Fix] [TAO-8952](https://oat-sa.atlassian.net/browse/TAO-8952) Add drag and scroll on the associate interaction [#1325](https://github.com/oat-sa/extension-tao-itemqti/pull/1325)
=> Release sprint 109 update 5

composer.json, composer.lock
=> release 111

composer.json, composer.lock
=> update tao core version

composer.json, composer.lock
Fixes the npm package update for tao-itemqti and tao-testqti.
=> Release sprint 112.1

composer.json, composer.lock
- _Feature_ [MS-22](https://oat-sa.atlassian.net/browse/MS-22) : webhook funxtionality [#302](https://github.com/oat-sa/extension-tao-delivery-rdf/pull/302)
- _Fix_ [MS-22](https://oat-sa.atlassian.net/browse/MS-22) : Remove DeliveryFactoryTest as it requires changes in code to perform … [#304](https://github.com/oat-sa/extension-tao-delivery-rdf/pull/304) ( by [bartlomiejmarszal](https://github.com/bartlomiejmarszal) - validated by [bartlomiejmarszal](https://github.com/bartlomiejmarszal) )
=> Release sprint 121 taskqueue bugfix

composer.json, composer.lock
https://github.com/oat-sa/extension-tao-itemqti/pull/1424
=> refresh metadata properties and headers

composer.json, composer.lock
Fixed: https://github.com/oat-sa/extension-tao-outcome/pull/184
=> release-0.126.2-alpha

composer.json, composer.lock
oat-sa/extension-tao-outcome version updated
=> Release Sprint 129 alpha 1

composer.json, composer.lock
- _Fix_ [TCA-554](https://oat-sa.atlassian.net/browse/TCA-554) : refactor header and footer [#817](https://github.com/oat-sa/extension-tao-proctoring/pull/817) ( by [AnastasiaArcadia](https://github.com/AnastasiaArcadia) - validated by [jsconan](https://github.com/jsconan) )  
- _Fix_ [TBD-33](https://oat-sa.atlassian.net/browse/TBD-33) : : impossible to resume a timed out delivery execution [#818](https://github.com/oat-sa/extension-tao-proctoring/pull/818)
=> Release 0.129.4-alpha

composer.json, composer.lock
Released TAO Community with included [hotfix in taoDeliveryRdf](https://github.com/oat-sa/extension-tao-delivery-rdf/releases/tag/v11.7.0.1)
=> Release TAO Sprint 131 Update 3

composer.json, composer.lock
Include a [`taoTestQti` v38.19.7.1 backport](https://github.com/oat-sa/extension-tao-testqti/releases/tag/v38.19.7.1).
=> Release 0.133.2-alpha

composer.json, composer.lock
=> release TTD-94, BSA-199, BSA-208 and BSA-209

composer.json, composer.lock
=> release BSA-208

composer.json, composer.lock
=> release TAO-10460

composer.json, composer.lock
Release TAO Community v0.134.5-alpha
=> Release TAO Community v0.134.5-alpha

composer.json, composer.lock
=> Sprint 135

composer.json, composer.lock
- Fix of missed images in text reader interaction.
=> update taoQtiItem extension

composer.json, composer.lock
Ticket: https://oat-sa.atlassian.net/browse/DPF-652
=> Backport for DEPP authoring

composer.lock
added LTI skip overview custom parameter.
=> added LTI skip overview custom parameter

composer.json, composer.lock
=> Release sprint 142

composer.json, composer.lock
Release 0.143.2 alpha
- fixed tao-core lists rdf repository
=> Release 0.143.2 alpha

composer.json, composer.lock
Hot fix for https://oat-sa.atlassian.net/browse/PR-142
=> chore: Release v0.144.1-alpha

composer.json, composer.lock
=> Tao Community Release

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/CON-430
=> chore:  Backport/CON-430/update oat-sa/extension-tao-item to 6.6.1.3

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/CON-430
=> chore: updated tao-core

composer.json, composer.lock
**Issue**
https://oat-sa.atlassian.net/browse/CON-606
**Related PR**
https://github.com/oat-sa/extension-tao-itemqti/pull/1630
=> [Hotfix: CON-606] - Fix special character

composer.json, composer.lock
Hotfix update for taoQtiItem solving illegal character error when saving item
https://oat-sa.atlassian.net/browse/CON-634
=> Hotfix/con 634/fix illegal character error

composer.json, composer.lock
=> chore: sprint147.2

composer.json, composer.lock
Backport of taoQtiItem that contains missing bundle js files
=> update taoQtiItem in version 25.15.1.2

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/TR-597
Add translated messages (IT) for test end dialog.
=> Fix/TR-597 Trim text in test end dialog

composer.json, composer.lock
build: updated oat-sa/extension-tao-testqti 40.3.17
=> build: updated oat-sa/extension-tao-testqti 40.3.17

composer.json, composer.lock
- Fix: missaligment for testlist IE11
- Refactormove dependencies to composer
- [Feat - ]: Order interaction improvement
- Fix: restore ims pci state in review mode
- Fix: use e.target to get clicked link
- Fix: : remove sample data with tricky name caused issues for developers on MacOS
- Feature: store css within passages
- Feature: Support multiple column layout in passage
- Feature: use review renderer on result page
- Feature: add trace variables to csv export
- Fix: [: ] - Empty button results tab
- Fix: : Fixed QTI duration class name.
- Feature: Restarting tasks from the task queue
- Fix: inconsistent item duration
- Feature: improve pre caching behavior
- Feature: chore: update @oat-satao-test-runner-qti .19.0
- Fix: : fixed missing last timestamp updating
- Feature: save item …
=> chore: v0.150.0-alpha

composer.json, composer.lock
fix: update tao-core with fixed guzzle versions
=> Release v0.150.1-alpha

composer.json, composer.lock
Sprint 0.134.1.2
**Release notes**
- _Feature_ [TR-130](https://oat-sa.atlassian.net/browse/TR-130) : feat: Add a service for moving assets to an external storage [#1599](https://github.com/oat-sa/extension-tao-itemqti/pull/1599)
=> Sprint 134 Alpha 1 Update 2

composer.json, composer.lock
=> chore: dependency updates sprint 151

composer.json, composer.lock
=> Release sprint 152

composer.json, composer.lock
Related to: https://oat-sa.atlassian.net/browse/TR-1207
Requires: 
Backport of https://github.com/oat-sa/tao-core/pull/2920
=> Hotfix/TR-1207/Support locale format datetime in UTC

composer.json, composer.lock
Release notes
- Fix: rollback to support multiple types of request parameter 
- Fix: forward semicolon as default separator
- Feature: Tabular import - update internal documentation
- Feature: Text wrap pictures
- Fix: : correction in filename
- Fix: math expression is ruined after editing
- Feature: separate tasks for indx
=> chore: composer update

composer.json, composer.lock
Bumps extension-tao-mediamanager to [v12.4.1](https://github.com/oat-sa/extension-tao-mediamanager/releases/tag/v12.4.1)
=> [Backport] ADF-496 Remove on/off sections toggling in passage authoring

composer.json, composer.lock
Add `prefer-stable` to sprint 158 community composer
=> Add prefer-stable to community

composer.json, composer.lock
With this PR we will move develop to this same state as master, therefore we can create branch `release-2021-09` from develop.
=> Align Develop branch to Master

composer.json, composer.lock
**Ticket**
https://oat-sa.atlassian.net/browse/ADF-605
=> [Backport ADF-590] [Tabular Import]: The metadata values in the CSV are not imported when in field "Alias" user uses capital letters

composer.json, composer.lock
**Ticket**
https://oat-sa.atlassian.net/browse/ADF-605
=> [Backport ADF-590] [Tabular Import] + Translations

composer.json, composer.lock
**Related to:** https://oat-sa.atlassian.net/browse/AUT-1128
Backport of the task: https://oat-sa.atlassian.net/browse/AUT-571
=> Hotfix/aut 571/backport choice broken after put elements

composer.json, composer.lock
Ticket [RO-549](https://oat-sa.atlassian.net/browse/RO-549)
Add latest fixes for extension-tao-testtaker
=> Upgrade extension-tao-testtaker to 8.4.1.2

composer.json, composer.lock
**Related task:** https://oat-sa.atlassian.net/browse/AUT-1176
**Backport of the fix:** https://oat-sa.atlassian.net/browse/ADF-695
=> chore: update tao-core version

composer.json, composer.lock
update taoTestQti to 41.15.5 to get backported fix of:
- https://github.com/oat-sa/extension-tao-testqti/pull/2128
=> update taoTestQti to 41.15.5

composer.json, composer.lock
backport for [TR-1909](https://oat-sa.atlassian.net/browse/TR-1909)
=> chore: update oat-sa/extension-tao-outcomeui:9.4.3.5

composer.json, composer.lock
**Backport** for [AUT-1620](https://oat-sa.atlassian.net/browse/AUT-1620)
=> chore: backport extension-tao-mediamanager v12.18.2

composer.json, composer.lock
Backport for https://oat-sa.atlassian.net/browse/AUT-1619
=> chore: backport extension-tao-itemqti v28.24.2

composer.json, composer.lock
Related ticket: https://oat-sa.atlassian.net/browse/AUT-1620
=> chore: updated extension-tao-mediamanager to 12.20.4

composer.json, composer.lock
update bundle by bakported package:
[extension-tao-proctoring:19.7.3](https://github.com/oat-sa/extension-tao-proctoring/releases/tag/v19.20.7.3)
=> Backport TR-3297

composer.json, composer.lock
update composer.json by backports for TR-3469
=> release backports for tr-3469

composer.json, composer.lock
=> Backport tr1909 for premium `nov` lts 

composer.lock
=> backport oatsd-1726 and 1707 to February LTS

composer.json, composer.lock
Backport: https://github.com/oat-sa/extension-tao-outcomeui/releases/tag/v9.5.0.2
Related ticket: https://oat-sa.atlassian.net/browse/NSA-227
=> chore: backport NSA-227 fix

composer.json, composer.lock
=> Backport `extension-tao-proctoring` for OATSD-1664 

composer.json, composer.lock
backport to november lts https://oat-sa.atlassian.net/browse/TR-3588
=> backport tr-3588

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/TR-3588
=> backport tr-3588 feb-lts

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/TR-3588
=> backport tr-3588 for march 

composer.json, composer.lock
[Original PR](https://github.com/oat-sa/extension-tao-mediamanager/pull/385)
=> chore: update extension-tao-mediamanager to 12.21.3

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-665
- While editing a resource, property labels are translated based on User Interface language.
=> fix: make properties label searchable by language

composer.json, composer.lock
**Update taoQtiItem to version 28.19.14.4 to include:**
Backport of [AUT-2030](https://oat-sa.atlassian.net/browse/AUT-2030) Present in [version 28.19.14.3](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/28.19.14.3)
Fix: border lines in table head in match interaction table
And:
[AUT-2031](https://oat-sa.atlassian.net/browse/AUT-2030) and [AUT-2038](https://oat-sa.atlassian.net/browse/AUT-2038) (PR included in 2031)
Fix: add missing translations in French for "don't save" "add column" and "add row"
[AUT-1935](https://oat-sa.atlassian.net/browse/AUT-1935)
Fix: Text in menu in French not fully visible
**What's Changed**
Hotfix/aut 2030/missing border lines head matrix table by [@Silvia-loza](https://github.com/Silvia-loza) in …
=> chore: update taoQtiItem to v28.19.14.4

composer.json, composer.lock
* tao-core updated from 50.10.0 to 50.10.1
=> [Fix] Use tokens from store

composer.json, composer.lock
* tao-core updated from 48.75.5 to 48.75.6
=> [Hotfix][OATSD-1783] Use tokens from store

composer.json, composer.lock
Revert https://github.com/oat-sa/tao-core-sdk-fe/pull/135
Revert PR: https://github.com/oat-sa/tao-core-sdk-fe/pull/140
=> [Fix] Revert token store

composer.json, composer.lock
Revert https://github.com/oat-sa/tao-core-sdk-fe/pull/137
=> [Hotfix] Revert token store

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-709
=> [Backport] REL-709 Media manager shared stimulus migration

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-714
=> [Backport] REL-714 Form field translation fallback to default language

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-765 and https://oat-sa.atlassian.net/browse/REL-757
=> [Backport] REL-765 fix remote delivery result export

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/TR-4060
Integration PR of extension backport: https://github.com/oat-sa/extension-tao-testqti/pull/2266
Branched from https://github.com/oat-sa/tao-community/releases/tag/2022.05.1
Eventually to be used for https://github.com/oat-sa/tao-enterprise-nfer-enot 2022.05.x
=> [Backport] Feat/tr 4060/partially answered items non-default config

composer.json, composer.lock
Related to [OATSD-1881](https://oat-sa.atlassian.net/browse/OATSD-1881).
Updated `tao-core` to 46.14.10 including the fix.
=> fix: upgrade tao-core to 46.14.10

composer.json, composer.lock
Related to [OATSD-1881](https://oat-sa.atlassian.net/browse/OATSD-1881).
Update tao-item-qti extension to include the fix.
=> chore: update tao-itemqti

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/TR-4337
Integration of PR https://github.com/oat-sa/extension-tao-testqti/pull/2277 - check that PR for description, instructions, approvals
=> Fix/tr 4337/bundle javascript

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/REL-783
https://oat-sa.atlassian.net/browse/REL-775
=> fix: update oat-sa/generis and oat-sa/tao-core and oat-sa/extension-tao-outcomeui

composer.json, composer.lock
**Backport :**
- _Feature_ [AUT-2493](https://oat-sa.atlassian.net/browse/AUT-2493) : feat: add FR translations [#177](https://github.com/oat-sa/extension-tao-testqti-previewer/pull/177)
- _Feature_ [AUT-2290](https://oat-sa.atlassian.net/browse/AUT-2290) : feat: add missing FR translations [#2194](https://github.com/oat-sa/extension-tao-itemqti/pull/2194)
-  _Hotfix_ [TR-4315](https://oat-sa.atlassian.net/browse/TR-4315) : hotfix: keyboard navigation [#3584](https://github.com/oat-sa/tao-core/pull/3584)
=> Backport 2021.11 fixes

composer.json, composer.lock
Please, check: https://github.com/oat-sa/extension-tao-testqti/pull/2297
=> [NCC-399] Backport TR-4008 session state restoration

composer.json, composer.lock
Update oat-sa/extension-tao-itemqti-pci to version 8.2.3
=> Backport/TR-4575/Revert a fix breaking compliance with the IMS standard

composer.lock
tao-core pointing to wrong version
=> release: tao-core release updated

composer.json, composer.lock
**Changes**
- [TR-4257](https://oat-sa.atlassian.net/browse/TR-4257) : DEFAULT_ANONYMOUS_INTERFACE_LANG for anonymous user [#353](https://github.com/oat-sa/extension-tao-lti/pull/353)
- _Fix_ [REL-842](https://oat-sa.atlassian.net/browse/REL-842) : Disable advanced search for the extension [#355](https://github.com/oat-sa/extension-tao-lti/pull/355)
=> chore: update tao-lti

composer.json, composer.lock
Update extension-tao-clientdiag to 8.4.4
=> Release 2022.10.2

composer.json, composer.lock
update bundle by backported https://github.com/oat-sa/extension-tao-testqti/pull/2323
=> Update by backported extension-tao-testqti

composer.json, composer.lock
Backport of https://github.com/oat-sa/extension-tao-mediamanager/pull/435 to [tao-community](https://github.com/oat-sa/tao-community/blob/2022.10.5/composer.json#L57) on [Udir October release](https://github.com/oat-sa/tao-enterprise-udir/blob/2022.10.1/composer.json#L63).
=> fix: update composer

composer.json, composer.lock
Backport of
https://github.com/oat-sa/extension-tao-mediamanager/pull/435
https://github.com/oat-sa/extension-tao-mediamanager/pull/441
https://github.com/oat-sa/extension-tao-mediamanager/pull/444
To [November release](https://github.com/oat-sa/tao-community/blob/release-2022-11/composer.json)
=> fix: AUT-2725, TR-4800, AUT-2637

composer.json, composer.lock
include backported fix: https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.14.4.1
=> chore: include AUT-2774 fix

composer.json, composer.lock
Backport of [AUT-2716](https://oat-sa.atlassian.net/browse/AUT-2716) to Dec. release branch
=> fix: add backport for AUT-2716

composer.json, composer.lock
=> release: release changes in qti test extension

composer.json, composer.lock
**Related to:** [TR 4637 ](https://oat-sa.atlassian.net/browse/TR-4637)
Update **PCI extension** version by one  to include fix in January release. 
https://github.com/oat-sa/extension-tao-itemqti-pci/releases/tag/v8.6.3
=> fix: update pci extension to include TR-4637 fix

composer.json, composer.lock
Backporting of https://oat-sa.atlassian.net/browse/TR-5000
=> Hotfix/tr 5000/itemqti eliminate label

composer.json, composer.lock
related to https://oat-sa.atlassian.net/browse/TR-5000
This is update of extension-tao-itemqti to 29.14.4.6 which contains fix rot mentioned ticket
Check fix is applied
=> hotfix/TR-5000/composer-require-oat-sa/extension-tao-itemqti:29.14.4.6

composer.json, composer.lock
related to https://oat-sa.atlassian.net/browse/TR-5000
Description
This is update of extension-tao-itemqti to 29.15.4 which contains fix rot mentioned ticket
How to test
Check fix is applied
=> hotfix/TR-5000/composer-require-oat-sa/extension-tao-itemqti:29.15.4

composer.json, composer.lock
related to https://oat-sa.atlassian.net/browse/TR-5000
Description
This is update of extension-tao-itemqti to 29.18.1.1 which contains fix rot mentioned ticket
How to test
Check fix is applied
=> hotfix/TR-5000/composer-require-oat-sa/extension-tao-itemqti:29.18.1.1

composer.json, composer.lock
Related to [LSI-1550](https://oat-sa.atlassian.net/browse/LSI-1550)
=> backport: fix search by label

composer.json, composer.lock
This Pull Request aims at integrating RE-762 in `tao-community` 2022.08.
=> fix: backport of RE-762 Trace Variables issue.

composer.json, composer.lock
The PR aims at backporting [NSA-314](https://oat-sa.atlassian.net/browse/NSA-314) to `tao-community`.
=> fix: backport of NSA-314. Missing next button translation lt-LT.

composer.json, composer.lock
update by backports for [TR-4934](https://oat-sa.atlassian.net/browse/TR-4934)
- https://github.com/oat-sa/tao-core/releases/tag/v46.8.5.2
- https://github.com/oat-sa/extension-tao-lti/releases/tag/v11.14.0.1
=> backport tr4934

composer.json, composer.lock
Related to: https://oat-sa.atlassian.net/browse/AUT-2882
Backport of AUT-2882 to November 2022 release https://github.com/oat-sa/extension-tao-testqti/releases/tag/v44.22.8
=> fix: backport AUT-2882 to November

composer.json, composer.lock
New revision for 2023-01 release including AUT-2852 fix for broken export caused by texReader PCI migration script
=> fix: include AUT-2852 fix

composer.json, composer.lock
Related to: https://oat-sa.atlassian.net/browse/LSI-1825
Backport https://github.com/oat-sa/tao-core/releases/tag/v50.25.1.5
=> Hotfix/LSI-1825/create Item  or class from sub classes from search result

composer.json, composer.lock
Related to: https://oat-sa.atlassian.net/browse/INV-639
Backport : https://github.com/oat-sa/extension-tao-ltideliveryprovider/releases/tag/v12.12.6
=> Hotfix/INV-639/ Showing "Attempts limits has reached" message when taking a test in TT portal if Max. Executions value is given as empty

composer.json, composer.lock
Backport of https://github.com/oat-sa/extension-tao-itemqti/pull/2341 to [March "oat-sa/extension-tao-itemqti": "29.21.2"](https://github.com/oat-sa/tao-community/blob/2023.03.2/composer.json#L39)
=> hotfix: use flag to skip replaceNonBreakingSpaceCharacters

composer.json, composer.lock
Backport taoQtiItem 29.21.2.3 with missing bundles
=> backport: taoQtiItem 29.21.2.3

composer.json, composer.lock
Release 2023.05.1 LTS
- Fix: guest user locale
=> chore: bump generis version

composer.json, composer.lock
coming from backport task [https://oat-sa.atlassian.net/browse/AUT-3093](https://oat-sa.atlassian.net/browse/AUT-3093)
changelog: updates tao qti item extension version
=> chore: updates tao qti item extension

composer.json, composer.lock
Missing fix in August release
Related to : 
https://oat-sa.atlassian.net/browse/REL-1234
https://oat-sa.atlassian.net/browse/REL-1164
=> deploy: oat-sa/extension-tao-lti:15.13.2

composer.json, composer.lock
Backport of issue [COECDP25-37](https://oat-sa.atlassian.net/browse/COECDP25-37) for august release
[COECDP25-37]: https://oat-sa.atlassian.net/browse/COECDP25-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: locale value parsing by including subtags

composer.json, composer.lock
* https://github.com/oat-sa/tao-core/pull/3875
* https://github.com/oat-sa/extension-tao-task-queue/pull/169
=> [Backport][Fix] Process tasks based on worker free space

composer.json, composer.lock
This reverts commit 86237e5719e07e60d5bf6538c9d638d49cb1bb01, reversing changes made to 7f2d596fe38841a755c371c57bbf3386b67a92f6.
=> Revert "Merge pull request #526 from oat-sa/release-2023.08.4"

composer.json, composer.lock
* https://github.com/oat-sa/extension-tao-itemqti/pull/2393
* https://github.com/oat-sa/extension-tao-itemqti/pull/2394
[AUT-3264]: https://oat-sa.atlassian.net/browse/AUT-3264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update oat-sa/extension-tao-itemqti to 30.2.3.1

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/ADF-1606
=> fix: backport ADF-1606

composer.json, composer.lock
* fix: Add fallback when no registration available or FF TAO_AS_A_TOOL is disabled in https://github.com/oat-sa/extension-tao-lti/pull/392
**Full Changelog**: https://github.com/oat-sa/tao-community/compare/2023.11...2023.11.1
=> Release 2023.11.1

composer.json, composer.lock
fix: Remove new container usage from migration - https://github.com/oat-sa/extension-tao-outcomeui/pull/486
=> Release 2023.11.2

composer.json, composer.lock
Hotfix for https://github.com/oat-sa/extension-tao-itemqti/pull/2422
=> chore: Shuffle label fix

composer.json, composer.lock
[Backport](https://oat-sa.atlassian.net/browse/AUT-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) Get Country Code Language List by @bartlomiejmarszal in https://github.com/oat-sa/tao-core/pull/3945
https://github.com/oat-sa/tao-core/releases/tag/v53.12.1.1
=> deploy: hotfix backport

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-1418 and https://oat-sa.atlassian.net/browse/REL-985
=> fix: include cache warmup fix in 2024.01

composer.json, composer.lock
oat-sa/extension-tao-testqti": "48.1.1.1"
=> deploy: backport oat-sa/extension-tao-testqti v48.1.1.1

composer.json, composer.lock
=> backport: oat-sa/extension-tao-testqti 48.1.1.1

composer.json, composer.lock
[TR-5940]: https://oat-sa.atlassian.net/browse/TR-5940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump generis and tao-delivery versions

composer.json, composer.lock
update tao-core by backport of [TR-6036](https://oat-sa.atlassian.net/browse/TR-6036)
[TR-6036]: https://oat-sa.atlassian.net/browse/TR-6036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update tao-core by 54.2.3

composer.json, composer.lock
Revert FEATURE_FLAG_TAO_AS_A_TOOL removal
=> fix: add fix for installation issue

composer.json, composer.lock
update oat-sa/extension-tao-itemqti to 30.10.1
=> chore: bump oat-sa/extension-tao-itemqti to 30.10.1

composer.json, composer.lock
=> fix: fix install

composer.json, composer.lock
Backport for https://oat-sa.atlassian.net/browse/RFE-1283
The changes are: https://github.com/oat-sa/extension-tao-outcomeui/pull/492/files
=> chore: backport for RFE-1283

composer.json, composer.lock
This aims to include version with a hotfix
=> fix: bump up extension-tao-testqti to 48.4.2

composer.json, composer.lock
Update oat-sa/extension-tao-lti to version 15.19.3
=> release: update taoLti to 15.19.3

composer.json, composer.lock
Fix broken TaoLti `\oat\taoLti\models\classes\theme\PortalThemeService` registration
=> chore: update taoLti

composer.json, composer.lock
Backport
tao-core - 54.14.3.1
https://github.com/oat-sa/tao-core/releases/tag/v54.14.3.1
=> release: 2024.06.2

composer.json, composer.lock
Fixes SOLAR-777. Removed FEATURE_FLAG_TAO_AS_A_TOOL.
=> Fix SOLAR-777 remove FEATURE_FLAG_TAO_AS_A_TOOL

composer.json, composer.lock
=> chore: backport 2024.06.3

composer.json, composer.lock
Backport https://github.com/oat-sa/tao-core/pull/4062
https://oat-sa.atlassian.net/browse/ADF-1728
=> chore: update tao-core

composer.json, composer.lock, coverage_badge.svg
This will fix issues recognized by QA related to MoveTo action and metadata export/import
=> Fix ADF-1741 MoveTo for classes and AUT-3750 metadata import/export

composer.json, composer.lock
Backport https://oat-sa.atlassian.net/browse/SOLAR-778
=> chore: backport SOLAR-778

composer.json, composer.lock
includes only backported fix - https://github.com/oat-sa/tao-core/pull/4080
https://oat-sa.atlassian.net/browse/ADF-1728 / https://oat-sa.atlassian.net/browse/LSI-4487
=> chore: backport ADF-1728 to june community release

composer.json, composer.lock
Related to https://oat-sa.atlassian.net/browse/REL-1731
To include https://oat-sa.atlassian.net/browse/AUT-3694
=> Update tao-core dependency

composer.json, composer.lock
Keeping `master` up to date with last patch
=> Updating master with 2024.08.1 patch

composer.json, composer.lock
https://github.com/oat-sa/tao-core/releases/tag/v54.20.1
=> chore: update 2024-09 with fixes from tao-core

composer.json, composer.lock
Include AUT-3795 for fixing missed Item Author role for LTI users
=> chore: add missed role ItemAuthor fro LTI Users

composer.json, composer.lock
=> chore: Backport solar-1020

composer.json, composer.lock
Ticket: https://oat-sa.atlassian.net/browse/AUT-4007
- update php version to 8.1
- https://github.com/oat-sa/tao-community/pull/648
=> feature: update php version to 8.1

composer.json, composer.lock
Backport of https://oat-sa.atlassian.net/browse/LSI-5002 on top of 2024.09.7 version (into 2024.09.8)
=> fix: booklet download

composer.json, composer.lock
Backport for https://oat-sa.atlassian.net/browse/INF-291
=> chore: backport for INF-291

composer.json, composer.lock
Tickets:
-  https://oat-sa.atlassian.net/browse/INF-302
-  https://oat-sa.atlassian.net/browse/INF-303 
-  https://oat-sa.atlassian.net/browse/INF-304
Fixed:
-  INF-302 - ability to save empty identifier
-  INF-303 - ability to save duplicated identifier
-  INF-304 - problem after saving duplicated identifier
=> backport: INF-302, INF-303, INF-304

composer.json, composer.lock
Release backport of https://github.com/oat-sa/tao-core-ui-fe/pull/615
=> chore: backport LSI-5002 fix

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/INF-314
Bring the fix
- https://github.com/oat-sa/extension-tao-testqti/pull/2595
to the latest release candidate.
=> Fix/INF-314/Revert empty value of serialized timeConstraint to null

composer.json, composer.lock
https://oat-sa.atlassian.net/browse/INF-284
Bring the fix
- https://github.com/oat-sa/extension-tao-itemqti-pci/pull/430
to the latest release candidate.
=> chore: update itemQtiPci to 8.16.5

composer.json, composer.lock
Backport for metadata export fix
=> backport: taoQtiTest 48.20.1.1 AUT-4185

composer.json, composer.lock
https://github.com/oat-sa/tao-core/pull/4251
https://github.com/oat-sa/tao-core/releases/tag/v54.38.1
=> backport: tao-core 54.36.2.1

composer.json, composer.lock
Release https://oat-sa.atlassian.net/browse/ADF-1976
=> chore: release extensions

composer.json, composer.lock
* https://github.com/oat-sa/extension-tao-testqti/pull/2618
* https://github.com/oat-sa/qti-sdk/releases/tag/0.28.9
=> chore: backport INF-299 INF-337

composer.json, composer.lock
Apply 
https://github.com/oat-sa/tao-core/releases/tag/v54.36.2.6 
https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v30.38.4.5
=> chore: update tao-core & tao-item-qti for INF-295

composer.json, composer.lock
Follow to https://github.com/oat-sa/extension-tao-testqti/pull/2643
=> chore: update testqti to 48.21.3

composer.json, composer.lock
Follow-up for https://github.com/oat-sa/extension-tao-testqti/releases/tag/v48.20.6.5
Follow-up for https://github.com/oat-sa/extension-tao-itemqti-pci/releases/tag/v9.0.0.1
=> chore: update testqti -> 48.20.6.5; update itemqti-pci -> itemqti-pci
