composer.json
composer.lock

Sprint 106.1
- _Fix_ [NEX-19](https://oat-sa.atlassian.net/browse/NEX-19) : update the provider with a wrong bundle [#1544](https://github.com/oat-sa/extension-tao-testqti/pull/1544) ( by [krampstudio](https://github.com/krampstudio) - validated by [btamas](https://github.com/btamas) )

Sprint 106.1 - fix taoQtiTest

---

composer.json
composer.lock

- [#48](https://github.com/oat-sa/extension-tao-outcomekeyvalue/pull/48) Fix version of required `generis` version in `taoAltResultStorage`

Release sprint 109 update 4

---

composer.json
composer.lock

Version 0.106.2.7-alpha
**Backport :**
- [fix] [TAO-9100](https://oat-sa.atlassian.net/browse/TAO-9100) "Started at" filter doesn't work on proctoring screen [#732](https://github.com/oat-sa/extension-tao-proctoring/pull/732)

Version 0.106.2.7-alpha backport

---

composer.json
composer.lock

https://oat-sa.atlassian.net/browse/CON-175
taoMediaManager changes backported 
- Reduced queries count to RDS while building media tree at resource pickers

updated media manager

---

composer.json
composer.lock

Release 0.143.1 alpha
updated : https://github.com/oat-sa/tao-core/releases/tag/v46.8.3
Release notes :
Fix CGF-164 : the tt and guest pages are entirely blank #2749
Fix CON-316 : lists default language #2751

chore: updted tao-core

---

composer.json
composer.lock

- _Fix_ [TR-422](https://oat-sa.atlassian.net/browse/TR-422) : announce flagged items in the end test warning [#1964](https://github.com/oat-sa/extension-tao-testqti/pull/1964) ( by [jsconan](https://github.com/jsconan) - validated by [meefox](https://github.com/meefox) )

Update oat-sa/extension-tao-testqti to v40.3.12

---

composer.json
composer.lock

Update "oat-sa/extension-tao-itemqti" to [27.1.1](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v27.1.1)

Release v0.149.1-alpha

---

.github/workflows/release.yml
composer.json
composer.lock

This action supposed to fix (`ghtoolkit release prepare` broken since version were removed from manifest files) and automate this procedure: https://github.com/oat-sa/github-tools/wiki/Sprint-release-procedure#31-prepare-the-release-of-tao-community
Action triggers when new PR into `alpha` branch opened/reopened 
Action generates new `composer.json` and `composer.lock` files according to the latest released versions of extensions.
NOTE: versions in `composer.json` in this PR file was not changed. Just changed formatting and added two directives:
```
"prefer-stable": true,
"minimum-stability": "stable",
```
The workflow is the following:
1. create new `composer-release.json` file with all dependencies version set to `'*'`
2. do `composer update` to generate `composer-release.lock` file …

ci: release action

---

composer.json
composer.lock

This PR aims at adding the missing French translations for `extension-tao-clientdiag` into sprint 134. It seems we had the fix, but forgot to include it in `tao-enterprise-depp` (next release target) last year.

Upgrade extension-tao-clientdiag to 7.7.2.1

---

composer.json
composer.lock

**Associated Jira issue:** [AUT-1927](https://oat-sa.atlassian.net/browse/AUT-1927).
This pull request updates `composer.json` for the February release to point to [v6.6.2](https://github.com/oat-sa/extension-tao-backoffice/releases/tag/v6.6.2) fix version of TAO Backoffice.

chore: Update Backoffice to backport version v6.6.2

---

composer.json
composer.lock

Related to https://oat-sa.atlassian.net/browse/TR-3646
See last 2 comments in the ticket.
In April 2022 release, `extension-tao-testqti` is missing the fix for this ticket.
So we need to update it to https://github.com/oat-sa/extension-tao-testqti/releases/tag/v44.10.2
Note that this release also includes https://oat-sa.atlassian.net/browse/TR-3354 , but it looks ok to include it.

Hotfix/TR 3646/calculator ar arb translation

---

composer.json
composer.lock

Backport of https://github.com/oat-sa/tao-core/pull/3368 for https://oat-sa.atlassian.net/browse/TR-3785, targeting November release.

chore: update with backport for tr-2754

---

composer.json
composer.lock

Change the GitHub protocol to fix issue: 
```
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
npm ERR! 
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andremachado/.npm/_logs/2022-03-22T08_17_43_745Z-debug.log
```
found in: https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/569653512379/projects/ltnec01dep-code-update/build/ltnec01dep-code-update%3A4ad9c635-f10a-4586-a035-cfe2a4912716/?region=eu-west-1
please check : …

[FIXED] github protocol

---

composer.json
composer.lock

* `oat-sa/extension-tao-eventlog` updated for `3.3.0` to `3.3.1`

[2022.02.2.1] Hotfix/Use legacy container in migration

---

composer.json
composer.lock

* `oat-sa/extension-tao-eventlog` updated for `3.3.0` to `3.3.1`

[2022.04] Fix/Use legacy container in migration

---

composer.json
composer.lock

* `oat-sa/extension-tao-eventlog` updated for `3.3.0` to `3.3.1`

[2022.03.3] Hotfix/Use legacy container in migration

---

composer.json
composer.lock

include [oat-sa/extension-tao-mediamanager v12.14.2.1](https://github.com/oat-sa/extension-tao-mediamanager/releases/tag/v12.14.2.1)

chore: include backported fix for mediamanager

---

composer.json
composer.lock

Related to https://oat-sa.atlassian.net/browse/TR-3287
- remove the git protocol from the package-lock to prevent issues installing the direct dependency

fix: update the protocol of the eve dependency

---

composer.json
composer.lock

Updates contain the latest hotfixes, which were applied to March and April releases.
Backports no needed, as path versions were introduced since code freeze.
**tao-core**: from 50.10.1 to 50.10.2
- Fix [REL-665](https://oat-sa.atlassian.net/browse/REL-665) : Checking empty value of label to avoid fatal errors https://github.com/oat-sa/tao-core/pull/3484
**qtiItemPci**: from 8.0.1 to 8.0.2
- Fix : chore: add missing bundle configuration https://github.com/oat-sa/extension-tao-itemqti-pci/pull/295

March release backports

---

composer.json
composer.lock

Updated TAO community to include: 
Included the option all on submittedVersion parameter to be able to export all submitted versions at once.
1. run the command:
```shell script
php index.php 'oat\taoOutcomeUi\scripts\task\ExportDeliveryResults' 'https://nmpp.nsa.etestavimas.lt#Delivery_2022spring_N2G81LTSL_1645454301' --columns=all --submittedVersion=all
```
2. check the output on `/path/to/tao/data/taskQueueStorage`

[Backport] included the option all on submittedVersion parameter #420

---

composer.json
composer.lock

**Associated Jira issue:** [ADF-1073](https://oat-sa.atlassian.net/browse/ADF-1073)
- https://github.com/oat-sa/extension-tao-itemqti/compare/v29.3.1...v29.3.2
---
---
```
root@d27cba9fa7e4:/var/www/html# php tao/scripts/taoUpdate.php 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.1.156:9003 (through xdebug.client_host/xdebug.client_port) :-(
Running extension update
generis already up to date
tao already up to date
taoResultServer already up to date
taoOutcomeRds already up to date
taoDelivery already up to date
taoBackOffice already up to date
taoTestTaker already up to date
taoGroups already up to date
taoItems already up to date
taoTests already up to date
taoQtiItem requires update from 29.3.1.0 to 29.3.2.0
Successfully updated taoQtiItem to 29.3.2.0 …
```

feat: Backport fix for item metadata importing to July 2022 release

---

composer.json
composer.lock

Related to https://oat-sa.atlassian.net/browse/TR-4339
It's merged into September, should be backported to May.
Include
https://github.com/oat-sa/extension-tao-test/releases/tag/v15.14.0
https://github.com/oat-sa/extension-tao-testqti-previewer/releases/tag/v3.6.0
https://github.com/oat-sa/extension-tao-item/releases/tag/v11.28.1
in the May release https://github.com/oat-sa/tao-community/releases/tag/2022.05.5
TAE in ticket comments

Hotfix/tr 4339/custom theme in previewer clientconfig may

---

composer.json
composer.lock

Related to: https://oat-sa.atlassian.net/browse/AUT-2713
Update oat-sa/extension-tao-itemqti to [v29.11.4](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.11.4)
Depends on:
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/319 to [September Release](https://github.com/oat-sa/tao-community/blob/2022.09.3/composer.json#L39) to [taoQtiItem v29.11.3](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.11.3/views/package.json#L12)

hotfix: oat-sa/extension-tao-itemqti to 29.11.4

---

composer.json
composer.lock

Related to: https://oat-sa.atlassian.net/browse/AUT-2713
Update oat-sa/extension-tao-itemqti to [29.12.4.2](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.12.4.2)
Depends on:
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/319 to [October Release](https://github.com/oat-sa/tao-community/blob/2022.10.2/composer.json#L39) in [taoQtiItem v29.12.4.1](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.12.4.1/views/package.json#L12)

Release 2022.10.3

---

composer.json
composer.lock

Update oat-sa/extension-tao-itemqti-pci to version 8.3.1
- _Fix_ [TR-4575](https://oat-sa.atlassian.net/browse/TR-4575) : Revert a fix breaking compliance with the IMS standard [#320](https://github.com/oat-sa/extension-tao-itemqti-pci/pull/320)

Fix/TR-4575/Revert a fix breaking compliance with the IMS standard

---

composer.json
composer.lock

Related to: https://oat-sa.atlassian.net/browse/AUT-1910
**Release 2022.10.07**
Update "oat-sa/extension-tao-itemqti" to  ["29.12.4.3"](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.12.4.3)
Backport of https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.14.4 to October release

fix: update "oat-sa/extension-tao-itemqti" to  "29.12.4.3"

---

composer.json
composer.lock

Backport to fix Assets with Styles:
Remove `mainClass` on Asset at saving: 
- https://github.com/oat-sa/extension-tao-mediamanager/pull/441
- https://github.com/oat-sa/extension-tao-mediamanager/pull/444
Fix the CSS format https://github.com/oat-sa/extension-tao-mediamanager/pull/421/commits/f50565216708c1770b647c333f12bdcba58688e3

fix: remove mainClass from user-styles

---

composer.json
composer.lock

Backport of => https://oat-sa.atlassian.net/browse/TR-4940
Updated taoQtiTest branch extension by one patch version to include the fix in January release

fix: update testQti extn. version  to include padding fix

---

composer.json
composer.lock

Using Release instead of inline alias on dependency oat-sa/extension-tao-testqti

fix: version attribute removed of the success response of the endpoint updateMetadata

---

composer.json
composer.lock

This PR aims at bringing some missing Italian (it-IT) translations for extension `oat-sa/extension-tao-clientdiag`.

fix: update extension taoClientDiag with latest version

---

composer.json
composer.lock

This backport aims at implementing [LSI-1770](https://oat-sa.atlassian.net/browse/LSI-1770) and [LSI-1771](https://oat-sa.atlassian.net/browse/LSI-1771) in 2022 November release.
[LSI-1770]: https://oat-sa.atlassian.net/browse/LSI-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LSI-1771]: https://oat-sa.atlassian.net/browse/LSI-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: backport LSI-1770 for missing Italian translations (diag)

---

composer.json
composer.lock

Enable new html tags functionality for March release of Tao community.

fix: add version 29.21.0 with html clean up functionality

---

composer.json
composer.lock

Ticket: https://oat-sa.atlassian.net/browse/NSA-353
The reason which caused this issue is the ticket RE-255 which was supposed to fix an issue on the export UI. The side effect was that the fields were also removed from CLI. Now both bugs should be fixed with these changes
Refs: https://oat-sa.atlassian.net/browse/RE-255
Refs: https://oat-sa.atlassian.net/browse/NSA-353
- please check: https://oat-sa.atlassian.net/browse/RE-255
- please check: https://oat-sa.atlassian.net/browse/NSA-353

[BACKPORT] [NSA-353] cli exports are missing critical fields #461

---

composer.json
composer.lock

Release 2023.03
<details>
<summary>Release Notes</summary>
- Feature: text reader migration script improvements
- Fix: text reader PCI script
- migration
- Fix: : updated translations for it-IT
- migration
- chore: update generis tao-core
- Fix: change norwegian translation access control
- Fix: : Preserve resource acl for moved resources
- Fix: : repair failing test on PHP8.1
- Fix: Propagating result variables via cli command
- migration
- Fix: : remove not working code and fix PHP8 compatibility
- chore: update generis tao-core
- Fix: : media manager is braking taoUpdate
- Fix: add allow copy to mathentry
- Featsanitizer in Math pci
- Fix: : missing modules element
- Fix: : uninstall script for the extension
- Feature: feat: add merging and cleaning of html sibling tags
- Fix: update …

Release 2023 03

---

.github/workflows/continuous-integration.yaml

This PR addresses the following deprecations in the GitHub Actions workflow
1. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
2. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
It also fixes unwanted concurrent jobs cancellations.
**Before**

Fix – Eliminate ci workflow deprecations

---

composer.json
composer.lock

This PR aim to provide proper ims pic export into older version of package
reason - https://oat-sa.atlassian.net/browse/OATSD-2386?focusedCommentId=220578
target releases:
- https://github.com/oat-sa/tao-enterprise-depp/releases/tag/v2021.11.50

Backport for Ims Pci export fix

---

composer.json
composer.lock

Backport of https://github.com/oat-sa/extension-tao-itemqti/pull/2341 to [April "oat-sa/extension-tao-itemqti": "29.21.2"](https://github.com/oat-sa/tao-community/blob/2023.04/composer.json#L39) release

hotfix: use flag to skip replaceNonBreakingSpaceCharacters

---

.github/workflows/continuous-integration.yaml

This PR squashes the whole https://github.com/oat-sa/tao-community/tree/gh-pages history into a single commit, so that the changes' history gets garbage collected and doesn't require additional disk space.

fix: squash gh-pages history

---

composer.json
composer.lock

Backport: https://github.com/oat-sa/extension-tao-itemqti/pull/2334
fixes overflow on associate interaction
if choice contains mathjax, it will stretch
images will now be limited to 180px max-width by CSS
Backport: https://github.com/oat-sa/extension-tao-itemqti/pull/2332
We are using JQuery UI draggable v1.9.2, that has issue with RTL https://bugs.jqueryui.com/ticket/4994
We can't update it, because we use JQuery lib v1.9.1
Fix: pass dir=rtl to widget inside columns and set dir=ltr for grid by css - see views/scss/item-creator.scss
Fix: clean code in views/js/qtiCreator/editor/gridEditor/resizable.js

backport: add fixess for MCA

---

composer.lock

Update funcacl to new version withou any js bundles in it, only translations.
More info: https://github.com/oat-sa/extension-tao-funcacl/commit/4fbc4289df577384127866127b44422f1e26a53f

fix: update funcacl commit to do not add bundles

---

.github/workflows/continuous-integration.yaml

This PR enables client-side test and includes them into the report publication.
See https://github.com/oat-sa/tao-community/actions/runs/5544605113/jobs/10122308704#step:11:444 and https://github.com/oat-sa/tao-community/pull/517#issuecomment-1634380856.
```
Execution Time (2023-07-13 14:55:02 UTC-0)
loading tasks                   1.1s  ▇ 2%
qunit:qtiitempcitest            4.2s  ▇▇ 6%
qunit:taotest                  11.6s  ▇▇▇▇▇▇ 17%
qunit:taoclientdiagnostictest   3.2s  ▇▇ 5%
qunit:taodeliveryrdf           833ms  ▇ 1%
qunit:taoitemstest             873ms  ▇ 1%
qunit:taomediamanagertest       2.1s  ▇ 3%
qunit:taoqtiitemtest           19.5s  ▇▇▇▇▇▇▇▇▇ 28%
qunit:taoqtitest                6.7s  ▇▇▇▇ 10%
qunit:taoqtitestpreviewer      15.7s  ▇▇▇▇▇▇▇▇ 23%
qunit:taotaskqueuetest          1.6s …
```

feat: add front-end tests

---

composer.json
composer.lock

* [v53.6.0](https://github.com/oat-sa/tao-core/releases/tag/v53.6.0)
* https://github.com/oat-sa/tao-core/pull/3875
* https://github.com/oat-sa/tao-core/compare/v53.4.2...v53.6.1
* [v6.8.1](https://github.com/oat-sa/extension-tao-task-queue/releases/tag/v6.8.1)
* https://github.com/oat-sa/extension-tao-task-queue/pull/171
* [v6.8.2](https://github.com/oat-sa/extension-tao-task-queue/releases/tag/v6.8.2)
* https://github.com/oat-sa/extension-tao-task-queue/pull/171
* [v53.4.3](https://github.com/oat-sa/tao-core/releases/tag/v53.4.3)
* https://github.com/oat-sa/tao-core/pull/3867
* [v53.4.4](https://github.com/oat-sa/tao-core/releases/tag/v53.4.4)
* https://github.com/oat-sa/tao-core/pull/3870
* [v53.5.0](https://github.com/oat-sa/tao-core/releases/tag/v53.5.0)
* …

chore: backport ADF-1571 fix to september release

---

composer.json
composer.lock

**Associated Jira issue:** [AUT-3264](https://oat-sa.atlassian.net/browse/AUT-3264)
**Changelog:** 
- Update oat-sa/extension-tao-itemqti: https://github.com/oat-sa/extension-tao-itemqti/compare/v30.2.0...v30.2.3
**taoUpdate**
```
root@b1f3613d9319:/var/www/html# php tao/scripts/taoUpdate.php 
Running extension update
generis already up to date
tao already up to date
taoResultServer already up to date
taoOutcomeRds already up to date
taoDelivery already up to date
taoBackOffice already up to date
taoTestTaker already up to date
taoGroups already up to date
taoItems already up to date
taoTests already up to date
taoQtiItem requires update from 30.2.0.0 to 30.2.3.0
Successfully updated taoQtiItem to 30.2.3.0
taoQtiTest already up to date
taoDeliveryRdf already up to date
taoOutcomeUi …
```

chore: Update oat-sa/extension-tao-itemqti

---

composer.json
composer.lock

Update taoQtiItem with version `v30.2.3.3` that contains compiled translations

fix: missing compiled translations

---

composer.json
composer.lock

Backport for: https://github.com/oat-sa/extension-tao-testtaker/pull/239
Changelog:
* `oat-sa/extension-tao-testtaker` version bumped

chore: backport - enforce default value for testtaker import

---

composer.json
composer.lock

Ticket: https://oat-sa.atlassian.net/browse/MS-2756
- Added UserPilot to TAO 3.x.
- https://github.com/oat-sa/extension-tao-lti/pull/400
- https://github.com/oat-sa/tao-core/pull/3967
- Install TAO Portal and TAO 3.x Authoring using NGS.
- Setup TAO Portal - Authoring simplification
- Login to TAO Portal
- Go to Authoring by clicking on Content Bank
- Inspect source code

Feature/ms 2756/add userpilot to tao 3.x v2

---

composer.json
composer.lock

Backport of https://github.com/oat-sa/extension-tao-testqti/pull/2461 to the May 2024 release

Backport/AUT-3414/Align categories that activate the TextToSpeech tool

---

composer.json
composer.lock

Update oat-sa/tao-core to [54.13.1 ](https://github.com/oat-sa/tao-core/releases/tag/v54.13.1)

chore: update 2024.06 release with RFE-1271

---

composer.json
composer.lock

Apply the Solar Design to the backoffice.
Integration of:
- https://github.com/oat-sa/tao-core/pull/4006
- https://github.com/oat-sa/tao-core/pull/4011
- https://github.com/oat-sa/tao-core/pull/4015
- https://github.com/oat-sa/tao-core/pull/4018
- https://github.com/oat-sa/tao-core/pull/4019
- https://github.com/oat-sa/tao-core/pull/4022
- https://github.com/oat-sa/tao-core/pull/4024
- https://github.com/oat-sa/tao-core/pull/4025
- https://github.com/oat-sa/tao-core/pull/4026
- https://github.com/oat-sa/tao-core/pull/4027
- https://github.com/oat-sa/extension-tao-itemqti/pull/2505
- https://github.com/oat-sa/extension-tao-testqti/pull/2473
- https://github.com/oat-sa/tao-core-ui-fe/pull/592
To activate the feature, you need the feature flag `FEATURE_FLAG_SOLAR_DESIGN_ENABLED`.
```sh
php …
```

Feature/RFE-1147/Apply the Solar Design

---

composer.json
composer.lock

Fix a blocking issue breaking any page load when a theme service does not inherit from `oat\tao\model\theme\ThemeService`.
Integration of:
- https://github.com/oat-sa/tao-core/pull/4029
To check if the Solar Design is enabled, the theme classes implement a check with respect to a feature flag. However, this check was placed in a parent class that is not inherited by all theme services.
This check is now moved to the abstract class.
- check out the branch: `git checkout -t origin/fix/AUT-3626/feature-flag-for-solar-design`
- log in to TAO backoffice
- the page should load
- activate the feature flag: `php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_SOLAR_DESIGN_ENABLED -v true`
- check that the Solar Design applies
Note: the issue arose with the extension …

Fix/RFE-1147/Apply the Solar Design

---

composer.json
composer.lock

Backport for https://oat-sa.atlassian.net/browse/RFE-1283
The changes are: https://github.com/oat-sa/extension-tao-outcomeui/pull/492/files

chore: backport for RFE-1283 into June release

---

composer.json
composer.lock

Update tao-core to version [54.14.3](https://github.com/oat-sa/tao-core/releases/tag/v54.14.3).
Fix another set of UI glitches in the backoffice when the Solar Design applies and a custom theme is already in place.
A few places were not following well the design:
- the tab selector when publishing a test (select local or remote)
- the buttons inside the item form (workflow buttons)
- the bottom bar for the look & feel (nice to have, but this would be hidden in the end)
The action bars in the lists and remote lists were hidden as they were considered empty.
- check out the branch: `git checkout -t origin/fix/ADF-1664/solar-design-glitches-part2`
- activate the feature flag: `php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_SOLAR_DESIGN_ENABLED -v true`
- …

release: update tao-core to 54.14.3

---

composer.json
composer.lock

oat-sa/extension-tao-testqti - 48.10.1 - fix importing QTI Packages without metadata

Release 2024.09.2

---

composer.json
composer.lock

oat-sa/extension-tao-testqti - 48.12.5 - fix importing QTI Packages without metadata

Stabilisation 2024.10

---

composer.json
composer.lock

Backport for `oat-sa/extension-tao-testqti-previewer` version
Ticket: [LSI-4788](https://oat-sa.atlassian.net/browse/LSI-4788)
[LSI-4788]: https://oat-sa.atlassian.net/browse/LSI-4788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: backport for LSI-4788

---

.github/workflows/continuous-integration.yaml

Remove the PHP 7.4 check as it is not supported anymore

chore: remove php 7.4 from continuous-integration.yaml

---

composer.json
composer.lock

Related to: https://oat-sa.atlassian.net/browse/AUT-1389
Deploy AUT-1389 in 2025-01 release.
Update oat-sa/extension-tao-itemqti to 30.25.2

fix: update oat-sa/extension-tao-itemqti to 30.25.2

---

composer.json
composer.lock

Backport of https://oat-sa.atlassian.net/browse/INF-279 into February RC

fix: backport ruby tags into RC

---

composer.json
composer.lock

Release 2025.05.1
Update `extension-tao-item` and `extension-tao-outcome` version

chore: update extensions versions
